version: '3.8'

services:

  backend:
    image: php:apache
    container_name: scandiweb_phpApache
    build: 
      context: ./api/docker
      dockerfile: Dockerfile
    
    volumes:
      - ./api:/var/www/html/scandiweb-junior-test-task
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql: 
    image: mysql:latest
    container_name: scandiweb_mysql
    environment:
      - MYSQL_DATABASE=scandiweb_junior_test
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./api/db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: scandiweb_phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql

  frontend:
      container_name: frontend
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
      - backend

#________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________#
  # Nginx
  # nginx:
    # image: nginx:latest
    # container_name: scandiweb_nginx
    # ports:
    #   - "80:80"
    # volumes:
    #   - ./api:/var/www
    #   - ./api/docker/default.conf:/etc/nginx/conf.d/default.conf

  # php:
  #   build:
  #     context: .
  #     dockerfile: ./api/docker/Dockerfile
  #   container_name: scandiweb_php
  #   volumes:
  #     - ./api:/var/www
  #   ports:
  #     - "9000:9000"