version: '3.8'

services:

  backend:
    image: php:apache
    container_name: scandiweb_test_phpApache
    build: 
      context: ./api/docker
      dockerfile: Dockerfile
    
    volumes:
      - ./:/var/www/scandiweb-junior-test-task
    ports:
      - 8000:80

  mysql: 
    image: mysql:latest
    container_name: scandiweb_test_mysql
    environment:
      - MYSQL_DATABASE=scandiweb_junior_test
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: scandiweb_test_phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql


#________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________#

    # nginx:
  #   image: nginx:latest
  #   container_name: scandiweb_test_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  # php:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #   container_name: scandiweb_test_php
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - "9000:9000"