version: '3.8'

services:

  www:
      image: php:apache
      container_name: scandiweb_test_phpApache
      build: 
        context: ./docker
        dockerfile: Dockerfile
     
      volumes:
        - ./:/var/www/html
      ports:
        - 8000:8000

  mysql: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=scandiweb_junior_test
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306


#________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________#

    # nginx:
  #   image: nginx:latest
  #   container_name: scandiweb_test_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  # php:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #   container_name: scandiweb_test_php
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - "9000:9000"