version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: scandiweb_test_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7.37
    container_name: scandiweb_test_mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scandiweb_junior_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: scandiweb_test_php
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"